### ISSUE TITLE
give a chance to modify the request uri before log to sw collector

### ISSUE THREAD

**Issue by zpf1989** [OpenSkywalking/skywalking-netcore#49]
Hello there,thanks for your great job.
We have a case that all our requests point to only one controller and action,something like "http://ip:port/Common/Service",and we use reflection to invoke special method depending on parameters provided by HttpRequest body.
So it causes a thing that in SW UI,all request uri are like the same,except the ip and port.
And it is hard to find out the invoke trace easily.
It can be solved by seperate the controller and action for each api,but we have lots of old codes and it's too hard to do this.
**So is it possible that we have a chance to modify the request uri before setting the Tags.Url？**
**Maybe something like a Func?**
Please think about the case ,thanks!

**Comment by yuleyule66** [comment]
@zpf1989  Thank you for your feedback, let me answer your question.

First of all, “Tag Url” in Span is from the RequestUri property in the HttpRequestMessage extracted from DiagnosticsSource, HttpRequestMessage is sent by HttpClient, so for your case if you want to customize the RequestUri you need to change this after the HttpClient call. The value of the parameter, this looks difficult to achieve.

Then, let's try other ways. In skywalking-netcore, this setting Tag.Url is an internal function. Opening this function requires detailed discussion. I don't think this function will be provided externally because he belongs to special requirements.

For your scenario, you can extend your own implementation of HttpClientDiagnosticProcessor based on the skywalking-netcore framework.

**Comment by wu-sheng** [comment]
> Then, let's try other ways. In skywalking-netcore, this setting Tag.Url is an internal function. Opening this function requires detailed discussion. I don't think this function will be provided externally because he belongs to special requirements.

I just saw this discussion, and decide to move in. Open internal APIs for an auto instrumentation based agent is dangerous, we should consider this carefully. For specific `#tag` and `#log` internal APIs, we should provide some bridges to do so. 

Such as in SkyWalking Java, we provide way about an API interface and agent instrumentation bridge to do so:
1. SkyWalking manual SDK APIs: https://github.com/apache/incubator-skywalking/blob/master/docs/en/Application-toolkit-trace.md
1. OpenTracing API bridge. But I have to say, there are a lot of controversies for it, and it is actually a solution. **And be careful, please consider it as an external, and only external APIs only.** Because, in my OpenTracing APIs, they considers them by manual instrumentation and manual context propagation only, like always did in **go**, which is the primary language of OpenTracing native tracer, Jaeger. Span in OpenTracing is allowed to cross thread without any notification, SkyWalking java agent can't and wouldn't(at least for me) support that.

**Comment by wu-sheng** [comment]
> So is it possible that we have a chance to modify the request uri before setting the Tags.Url？
Maybe something like a Func?

Speaking of `Tags.Url`, in SkyWalking java or collector, we consider it is a list, which makes the tag's value unchangeable.  That is not a refer from me.

**Comment by zpf1989** [comment]
Ok,thanks for the advice and discussion.
Since my case is something special,but I really learn things from you guys.
Thank you again! @yuleyule66 @wu-sheng
